// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_ClavierDor.Data;

#nullable disable

namespace Projet_ClavierDor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423124545_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Projet_ClavierDor.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Questions sur le langage C#",
                            Titre = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Description = "SQL, ORM, SQLite",
                            Titre = "Base de données"
                        },
                        new
                        {
                            Id = 3,
                            Description = "HTML, CSS, Blazor",
                            Titre = "Web"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Logique et algorithmes",
                            Titre = "Algorithmie"
                        });
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Joker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Utilise")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartieId");

                    b.ToTable("Jokers");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Joueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Joueurs");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Partie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JoueurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoueurId");

                    b.ToTable("Parties");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BonneReponse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Difficulte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BonneReponse = "int",
                            CategorieId = 1,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Quel mot-clé permet de déclarer une variable entière en C# ?"
                        },
                        new
                        {
                            Id = 2,
                            BonneReponse = "== compare les références, .Equals() compare les valeurs",
                            CategorieId = 1,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Quelle est la différence entre '==' et '.Equals()' en C# ?"
                        },
                        new
                        {
                            Id = 3,
                            BonneReponse = "Une classe qui ne peut pas être instanciée directement",
                            CategorieId = 1,
                            Difficulte = "Moyen",
                            Points = 2,
                            Texte = "Qu'est-ce qu'une classe abstraite en C# ?"
                        },
                        new
                        {
                            Id = 4,
                            BonneReponse = "Language Integrated Query, permet d'interroger des collections",
                            CategorieId = 1,
                            Difficulte = "Moyen",
                            Points = 2,
                            Texte = "Qu'est-ce que le LINQ en C# ?"
                        },
                        new
                        {
                            Id = 5,
                            BonneReponse = "Une classe enfant hérite des propriétés et méthodes de la classe parent",
                            CategorieId = 1,
                            Difficulte = "Boss",
                            Points = 3,
                            Texte = "Expliquez le principe de l'héritage en POO."
                        },
                        new
                        {
                            Id = 6,
                            BonneReponse = "Structured Query Language",
                            CategorieId = 2,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Que signifie SQL ?"
                        },
                        new
                        {
                            Id = 7,
                            BonneReponse = "SELECT",
                            CategorieId = 2,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Quelle commande SQL permet de récupérer des données ?"
                        },
                        new
                        {
                            Id = 8,
                            BonneReponse = "Une colonne qui référence la clé primaire d'une autre table",
                            CategorieId = 2,
                            Difficulte = "Moyen",
                            Points = 2,
                            Texte = "Qu'est-ce qu'une clé étrangère ?"
                        },
                        new
                        {
                            Id = 9,
                            BonneReponse = "Object Relational Mapper, fait le lien entre objets C# et tables SQL",
                            CategorieId = 2,
                            Difficulte = "Moyen",
                            Points = 2,
                            Texte = "Qu'est-ce qu'un ORM ?"
                        },
                        new
                        {
                            Id = 10,
                            BonneReponse = "INNER JOIN retourne uniquement les correspondances, LEFT JOIN retourne tout de la table gauche",
                            CategorieId = 2,
                            Difficulte = "Boss",
                            Points = 3,
                            Texte = "Quelle est la différence entre INNER JOIN et LEFT JOIN ?"
                        },
                        new
                        {
                            Id = 11,
                            BonneReponse = "HyperText Markup Language",
                            CategorieId = 3,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Que signifie HTML ?"
                        },
                        new
                        {
                            Id = 12,
                            BonneReponse = "Cascading Style Sheets, langage de mise en forme des pages web",
                            CategorieId = 3,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Qu'est-ce que le CSS ?"
                        },
                        new
                        {
                            Id = 13,
                            BonneReponse = "Framework C# pour créer des interfaces web interactives",
                            CategorieId = 3,
                            Difficulte = "Moyen",
                            Points = 2,
                            Texte = "Qu'est-ce que Blazor ?"
                        },
                        new
                        {
                            Id = 14,
                            BonneReponse = "Server s'exécute côté serveur, WebAssembly côté client dans le navigateur",
                            CategorieId = 3,
                            Difficulte = "Boss",
                            Points = 3,
                            Texte = "Quelle est la différence entre Blazor Server et Blazor WebAssembly ?"
                        },
                        new
                        {
                            Id = 15,
                            BonneReponse = "Une structure qui répète un bloc de code un nombre défini de fois",
                            CategorieId = 4,
                            Difficulte = "Facile",
                            Points = 1,
                            Texte = "Qu'est-ce qu'une boucle for ?"
                        },
                        new
                        {
                            Id = 16,
                            BonneReponse = "O(log n)",
                            CategorieId = 4,
                            Difficulte = "Boss",
                            Points = 3,
                            Texte = "Quelle est la complexité d'une recherche binaire ?"
                        },
                        new
                        {
                            Id = 17,
                            BonneReponse = "Une fonction qui s'appelle elle-même",
                            CategorieId = 4,
                            Difficulte = "Moyen",
                            Points = 2,
                            Texte = "Qu'est-ce que la récursivité ?"
                        });
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Reponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReponse")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReponseDonnee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartieId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Reponses");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Joker", b =>
                {
                    b.HasOne("Projet_ClavierDor.Models.Partie", "Partie")
                        .WithMany()
                        .HasForeignKey("PartieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partie");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Partie", b =>
                {
                    b.HasOne("Projet_ClavierDor.Models.Joueur", "Joueur")
                        .WithMany("Parties")
                        .HasForeignKey("JoueurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Joueur");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Question", b =>
                {
                    b.HasOne("Projet_ClavierDor.Models.Categorie", "Categorie")
                        .WithMany("Questions")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Reponse", b =>
                {
                    b.HasOne("Projet_ClavierDor.Models.Partie", "Partie")
                        .WithMany("Reponses")
                        .HasForeignKey("PartieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Projet_ClavierDor.Models.Question", "Question")
                        .WithMany("Reponses")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partie");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Categorie", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Joueur", b =>
                {
                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Partie", b =>
                {
                    b.Navigation("Reponses");
                });

            modelBuilder.Entity("Projet_ClavierDor.Models.Question", b =>
                {
                    b.Navigation("Reponses");
                });
#pragma warning restore 612, 618
        }
    }
}
